# Generated by Django 4.2.3 on 2023-07-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_book_publication_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="publication_date",
            field=models.DateTimeField(),
        ),
    ]
