# Generated by Django 4.2.3 on 2023-07-04 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_book_publication_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="publication_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
